# tasks file for iteasy.ansible.roles.webhost_manager
- name: Check if the user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ user_id }}"
  register: user_info
  failed_when: user_info is not defined or user_info is none
  ignore_errors: false  # 사용자가 없으면 실패하게 설정

- name: Ensure the user account is absent
  ansible.builtin.user:
    name: "{{ user_id }}"
    state: absent
    remove: yes  # 이 옵션을 통해 홈 디렉터리와 메일 스풀을 함께 삭제합니다.
  when: user_info is defined and user_info is not none
  register: user_deleted

- name: Remove user's home directory if it still exists
  ansible.builtin.file:
    path: "/home/{{ user_id }}"
    state: absent
  when: user_deleted.changed  # 계정 삭제가 이루어졌을 경우에만 실행됩니다.
  
- name: Remove user's mail spool if it still exists
  ansible.builtin.file:
    path: "/var/spool/mail/{{ user_id }}"
    state: absent
  when: user_deleted.changed  # 계정 삭제가 이루어졌을 경우에만 실행됩니다.

# DB
# - name: Create SQL file
#   copy:
#     dest: "/tmp/db_drop_{{ ansible_date_time.iso8601_basic_short }}.sql"
#     content: |
#       DROP DATABASE IF EXISTS {{ db_name }};
#       DROP USER IF EXISTS '{{ db_user }}'@'localhost';
- name: Create SQL file
  template:
    src: templates/removeDB.j2
    dest: "/tmp/db_drop_{{ ansible_date_time.iso8601_basic_short }}.sql"
  when: db_name is defined and db_name != "" and db_user is defined and db_user != ""

- name: Execute SQL file
  shell: mysql -u {{ mysql_root_user }} -p'{{ mysql_root_password }}' < /tmp/db_drop_{{ ansible_date_time.iso8601_basic_short }}.sql
  when: db_name is defined and db_name != "" and db_user is defined and db_user != ""

- name: Remove SQL file
  file:
    path: "/tmp/db_drop_{{ ansible_date_time.iso8601_basic_short }}.sql"
    state: absent
  when: db_name is defined and db_name != "" and db_user is defined and db_user != ""

# 쿼타 해제
# - name: Clear user's disk quota
#   command: "setquota -u {{ user_id }} 0 0 0 0 -a"
#   when: user_deleted.changed
#   register: quota_cleared

# - name: Check quota clearing result
#   debug:
#     msg: "Quota cleared for user {{ user_id }}"
#   when: quota_cleared.changed

# vhost 삭제
# TODO: 현재 vhost는 vhost.conf 파일에 모두 모여 있고
# TODO: 삭제하려면
# TODO: 해당 구성 파일에 대한 구문을 찾고
# TODO: 삭제하던지 주석처리를 하던지 해야하는데
# TODO: 이걸 어떻게 처리하는게 좋은것인가
- name: Remove vhost file
  file:
    path: "/etc/httpd/conf.d/{{ user_id }}_vhosts.conf"
    state: absent

- name: Remove cband file
  file:
    path: "/etc/httpd/conf.d/{{ user_id }}_cband.conf"
    state: absent
